### ISSUE TITLE
IPG项目数据准备以及环境部署

### ISSUE THREAD

**Issue by igotsmoke9** [huawei-noah/Efficient-Computing#144]
您好，我在复现您24年CVPR的 Image Processing GNN: Breaking Rigidity in Super-Resolution 论文时，在数据集准备这里遇到了问题，直接下载的数据集并没有划分为子文件，例如Urban100数据集
![微信图片_20240812144352](https://github.com/user-attachments/assets/a3cad62c-6a67-4a45-86b1-a595f3e0dc64)
以及我在配置虚拟环境的时候出现了ERROR: Could not build wheels for antlr4-python3-runtime, which is required to install pyproject.toml-based projects这个错误，希望能得到您的解答，谢谢！

**Comment by YuchuanTian** [comment]
Thank you for your interest in our work!

For the dataset: I guess the problem is that Urban100 only contains original ground truth images. We used an official MATLAB code provided by BasicSR to process these gt images (sorry but I lost the official link to the code; but I could provide a copy as follows).

For the error: actually I haven't encountered this strange error before. When (Installing which package) does this error pop up? I'd appreciate it very much if you could provide more information.

**Comment by Liu6767-creator** [comment]
我怎么没找到代码压缩包啊 救命 谁能发一下啊
