### ISSUE TITLE
[IPG] How to test model with multiple GPUs

### ISSUE THREAD

**Issue by Raymondmax** [huawei-noah/Efficient-Computing#149]
I want to test model with multiple GPUs, and tried to change the 'num_gpu' to 'auto', but the process still used only one GPU.
How you tested with multiple GPUs, how to change the configuration? @YuchuanTian

**Comment by YuchuanTian** [comment]
We apologize that testing on multiple GPUs is not supported so far. Actually, the problem is that the function ```dist_validation``` [here](https://github.com/huawei-noah/Efficient-Computing/blob/17bf441b3ecf5426701a3cd81d843f177bc3a8cf/LowLevel/IPG/basicsr/models/sr_model.py#L132) is not implemented for all ranks. I have checked the latest version of "basicsr" as well as some other implementations on GitHub, but unfortunately none of them have correctly implemented the function.

Apart from implementing this dist_validation function, I also suggest a modification of data loaders in support of distributed data parallel.

**Comment by Raymondmax** [comment]
Alright, thanks for the response.
