### ISSUE TITLE
Cannot reproduce the results of NetworkExpansion on DeiT-base for ImageNet-1k

### ISSUE THREAD

**Issue by Osilly** [huawei-noah/Efficient-Computing#63]
Thanks for providing the code of NetworkExpansion! I have some questions about the results of experiments on DeiT-base for ImageNet-1k. 

We firstly reproduce the results of origin DeiT-base with default settings on four GPUs (batch size 1024). The part of log is as follows:

```
{"train_lr": 9.999999999999953e-07, "train_loss": 6.934793044909013, "test_loss": 6.813265567517463, "test_acc1": 0.5400000160217285, "test_acc5": 2.1420000718688965, "epoch": 0, "n_parameters": 86567656}
{"train_lr": 9.999999999999953e-07, "train_loss": 6.880267438938101, "test_loss": 6.75039446080914, "test_acc1": 0.6880000291442872, "test_acc5": 2.8920000970458983, "epoch": 1, "n_parameters": 86567656}
...
{"train_lr": 0.0005153664978422618, "train_loss": 3.436933759066889, "test_loss": 1.0792683221911656, "test_acc1": 75.20200245117188, "test_acc5": 92.846002265625, "epoch": 149, "n_parameters": 86567656}
{"train_lr": 0.0005101835331375457, "train_loss": 3.437451235729632, "test_loss": 1.0756556817138467, "test_acc1": 75.12600234375, "test_acc5": 92.90800240234375, "epoch": 150, "n_parameters": 86567656}
{"train_lr": 0.0005049999999999881, "train_loss": 3.449057036357151, "test_loss": 1.090276759999399, "test_acc1": 75.11600233398437, "test_acc5": 92.84200287109375, "epoch": 151, "n_parameters": 86567656}
...
{"train_lr": 1.0976769428005425e-05, "train_loss": 2.6524045337065996, "test_loss": 0.8198514178054024, "test_acc1": 81.84800255859375, "test_acc5": 95.632002421875, "epoch": 295, "n_parameters": 86567656}
{"train_lr": 1.0678380296485761e-05, "train_loss": 2.644358063273007, "test_loss": 0.8194626951945647, "test_acc1": 81.8800025390625, "test_acc5": 95.65800232421876, "epoch": 296, "n_parameters": 86567656}
{"train_lr": 1.0434199101065237e-05, "train_loss": 2.639190801923319, "test_loss": 0.821070681318982, "test_acc1": 81.7740025, "test_acc5": 95.60800267578125, "epoch": 297, "n_parameters": 86567656}
{"train_lr": 1.0244252618963046e-05, "train_loss": 2.633857111588752, "test_loss": 0.8192249445514824, "test_acc1": 81.7660025, "test_acc5": 95.61800244140625, "epoch": 298, "n_parameters": 86567656}
{"train_lr": 1.0108561679951307e-05, "train_loss": 2.6339514840135188, "test_loss": 0.8184978038300085, "test_acc1": 81.81000259765625, "test_acc5": 95.630002421875, "epoch": 299, "n_parameters": 86567656}
```

We can get the best acc 81.88% in epoch 296. 

But for NetworkExpansion, we use the setting in readme (only add `--expand=deit_base_depth_6_12`). We cannot reproduce the results of NetworkExpansion. The part of log is as follows (`train_total_train_time` indicates that we only add the codes for counting the training time of each epoch):

```
{"train_lr": 9.999999999999953e-07, "train_loss": 6.942462879881489, "train_total_train_time": 500.1176945567131, "test_loss": 6.8271714421629, "test_acc1": 0.5280000178527832, "test_acc5": 2.1340000703430175, "epoch": 0, "n_parameters": 44040424, "ema_test_loss": 7.048604470172911, "ema_test_acc1": 0.08900000495910644, "ema_test_acc5": 0.48850001792907716}
{"train_lr": 9.999999999999953e-07, "train_loss": 6.886437099614589, "train_total_train_time": 492.2552005648613, "test_loss": 6.770169287237502, "test_acc1": 0.7480000204467774, "test_acc5": 2.700000115814209, "epoch": 1, "n_parameters": 44040424, "ema_test_loss": 7.035004312755498, "ema_test_acc1": 0.08800000350952149, "ema_test_acc5": 0.48850002090454103}
...
{"train_lr": 0.0005153664978422618, "train_loss": 3.845887410126144, "train_total_train_time": 467.33858823776245, "test_loss": 1.3238942614038482, "test_acc1": 70.5920021875, "test_acc5": 90.1140025390625, "epoch": 149, "n_parameters": 44040424, "ema_test_loss": 1.1737848250693037, "ema_test_acc1": 73.28900226806641, "ema_test_acc5": 91.46150255371094}
{"train_lr": 0.0005101835331375457, "train_loss": 3.6556288113506388, "train_total_train_time": 874.7216867208481, "test_loss": 1.2730122913841073, "test_acc1": 71.71000223632812, "test_acc5": 90.7580024609375, "epoch": 150, "n_parameters": 44040424, "ema_test_loss": 1.871516169482515, "ema_test_acc1": 60.1640017163086, "ema_test_acc5": 82.99900267578126}
{"train_lr": 0.0005049999999999881, "train_loss": 3.6446456812935577, "train_total_train_time": 874.09198564291, "test_loss": 1.2423403065168221, "test_acc1": 71.85000235351562, "test_acc5": 90.9000024609375, "epoch": 151, "n_parameters": 44040424, "ema_test_loss": 1.7114188970272777, "ema_test_acc1": 63.17400187255859, "ema_test_acc5": 85.10950283691406}
...
{"train_lr": 3.5854637045254126e-05, "train_loss": 2.7119328027530063, "train_total_train_time": 872.1285403966904, "test_loss": 0.9072413660642755, "test_acc1": 80.26800236328125, "test_acc5": 94.90200248046875, "epoch": 270, "n_parameters": 44040424, "ema_test_loss": 0.8434429074857981, "ema_test_acc1": 81.10050244628906, "ema_test_acc5": 95.41000252441407}
{"train_lr": 3.4227024433899046e-05, "train_loss": 2.7073332854359746, "train_total_train_time": 872.4541409015656, "test_loss": 0.8979384355417644, "test_acc1": 80.39600248046875, "test_acc5": 94.99000228515625, "epoch": 271, "n_parameters": 44040424, "ema_test_loss": 0.8440948654790871, "ema_test_acc1": 81.13550254394531, "ema_test_acc5": 95.39900247070312}
{"train_lr": 3.2651037384443736e-05, "train_loss": 2.7050206696005654, "train_total_train_time": 876.4675828814507, "test_loss": 0.8991356328243517, "test_acc1": 80.32800249023437, "test_acc5": 94.938002265625, "epoch": 272, "n_parameters": 44040424, "ema_test_loss": 0.8447734819341252, "ema_test_acc1": 81.12950255859376, "ema_test_acc5": 95.39850262207031}
...
{"train_lr": 1.0244252618963046e-05, "train_loss": 2.6277290844707655, "train_total_train_time": 870.9654639959335, "test_loss": 0.9040371188680634, "test_acc1": 80.4420026171875, "test_acc5": 95.0340028125, "epoch": 298, "n_parameters": 44040424, "ema_test_loss": 0.8685019163571241, "ema_test_acc1": 80.89550272460937, "ema_test_acc5": 95.24600236328125}
{"train_lr": 1.0108561679951307e-05, "train_loss": 2.628333218687539, "train_total_train_time": 871.8516836166382, "test_loss": 0.900406660924431, "test_acc1": 80.49400240234375, "test_acc5": 95.03600259765625, "epoch": 299, "n_parameters": 44040424, "ema_test_loss": 0.8693366821940619, "ema_test_acc1": 80.89100259277343, "ema_test_acc5": 95.24200244628906}
```

We can get the best acc 80.49% in epoch 299. And if we use the the ema acc, we can get the best acc 81.14% in epoch 271. We cannot reproduce the acc of 81.5%.

**Comment by dingning97** [comment]
Have you checked the env that you used for reproducing the result ?
We used python3.7 and "**numpy-1.21.6 && torch==1.7.0 && torchvision==0.8.1 && timm==0.3.2**" throughout the experiments.
Please use exactly the same because version difference might lead to slight performance difference.

We re-run the experiment on **8 V100 GPUs** using the codes in this repo and present the results below:
=============================================================
This is the training log file log.txt, the best result 81.49% happens at around the 275th epoch in log.txt:

{"train_lr": 3.926401936765786e-05, "train_loss": 2.6813198218909764, "test_loss": 0.8804734315384518, "test_acc1": 80.78200257568359, "test_acc5": 95.0160024887085, "epoch": 268, "n_parameters": 44040424, "ema_test_loss": 0.8248591553984266, "ema_test_acc1": 81.43400230926514, "ema_test_acc5": 95.51200281341552}
{"train_lr": 3.753369673244709e-05, "train_loss": 2.6685733140039023, "test_loss": 0.8836194227139155, "test_acc1": 80.6000023828125, "test_acc5": 95.01800250671387, "epoch": 269, "n_parameters": 44040424, "ema_test_loss": 0.8252994532160687, "ema_test_acc1": 81.42800236785888, "ema_test_acc5": 95.51800269622802}
{"train_lr": 3.585463704525412e-05, "train_loss": 2.6682173328386316, "test_loss": 0.8732348638727809, "test_acc1": 80.82800238098145, "test_acc5": 95.02400268157959, "epoch": 270, "n_parameters": 44040424, "ema_test_loss": 0.8257967208822569, "ema_test_acc1": 81.4440024520874, "ema_test_acc5": 95.50400265716553}
{"train_lr": 3.4227024433899046e-05, "train_loss": 2.6537569665865934, "test_loss": 0.8786587715148926, "test_acc1": 80.75800245025634, "test_acc5": 94.99600253753663, "epoch": 271, "n_parameters": 44040424, "ema_test_loss": 0.8262286731465296, "ema_test_acc1": 81.44800239074706, "ema_test_acc5": 95.50800261108398}
{"train_lr": 3.2651037384443736e-05, "train_loss": 2.656564011455154, "test_loss": 0.8731725564734503, "test_acc1": 80.87800235412598, "test_acc5": 95.02600247894287, "epoch": 272, "n_parameters": 44040424, "ema_test_loss": 0.8267017788056171, "ema_test_acc1": 81.47600238098144, "ema_test_acc5": 95.50600254272462}
{"train_lr": 3.112684872162703e-05, "train_loss": 2.6594721845133034, "test_loss": 0.8774344218951283, "test_acc1": 80.82000240936279, "test_acc5": 94.96000277191162, "epoch": 273, "n_parameters": 44040424, "ema_test_loss": 0.8272404183040966, "ema_test_acc1": 81.49000256652832, "ema_test_acc5": 95.49600264038087}
{"train_lr": 2.9654625589913e-05, "train_loss": 2.656300240462061, "test_loss": 0.8757588304579258, "test_acc1": 80.87600236572266, "test_acc5": 95.04600251800537, "epoch": 274, "n_parameters": 44040424, "ema_test_loss": 0.8277485564802632, "ema_test_acc1": 81.49400260925293, "ema_test_acc5": 95.4840026626587}
{"train_lr": 2.8234529435159726e-05, "train_loss": 2.643638891734475, "test_loss": 0.869553103478569, "test_acc1": 80.87200243713379, "test_acc5": 95.0720025793457, "epoch": 275, "n_parameters": 44040424, "ema_test_loss": 0.8282838651176655, **"ema_test_acc1": 81.49000264831542**, "ema_test_acc5": 95.48200264678955}
{"train_lr": 2.686671598691151e-05, "train_loss": 2.646190739626126, "test_loss": 0.8783499774607745, "test_acc1": 80.86600265594483, "test_acc5": 94.99200239257813, "epoch": 276, "n_parameters": 44040424, "ema_test_loss": 0.8288276872851632, **"ema_test_acc1": 81.49000267761231**, "ema_test_acc5": 95.48200267608642}
{"train_lr": 2.55513352413271e-05, "train_loss": 2.644771159421816, "test_loss": 0.8749298582022841, "test_acc1": 80.8840022531128, "test_acc5": 95.00400241485596, "epoch": 277, "n_parameters": 44040424, "ema_test_loss": 0.8293863606046546, **"ema_test_acc1": 81.49000264129639**, "ema_test_acc5": 95.49200275421143}
{"train_lr": 2.4288531444729954e-05, "train_loss": 2.643690174980034, "test_loss": 0.8759283736122377, "test_acc1": 80.87000252838135, "test_acc5": 95.05800261901855, "epoch": 278, "n_parameters": 44040424, "ema_test_loss": 0.8299828544259071, "ema_test_acc1": 81.44600266082763, "ema_test_acc5": 95.47800277374267}
{"train_lr": 2.3078443077785567e-05, "train_loss": 2.6363265993926737, "test_loss": 0.8795836784622886, "test_acc1": 80.89800265869141, "test_acc5": 94.97200266174316, "epoch": 279, "n_parameters": 44040424, "ema_test_loss": 0.8305524299767885, "ema_test_acc1": 81.44400238739014, "ema_test_acc5": 95.48800272766113}
{"train_lr": 2.192120284031953e-05, "train_loss": 2.6218885938159757, "test_loss": 0.8716517576214039, "test_acc1": 80.89200254119874, "test_acc5": 95.06200255981446, "epoch": 280, "n_parameters": 44040424, "ema_test_loss": 0.831194661106124, "ema_test_acc1": 81.42200238189697, "ema_test_acc5": 95.47000259521485}
{"train_lr": 2.0816937636766537e-05, "train_loss": 2.630097663326324, "test_loss": 0.8730329658949014, "test_acc1": 80.9560024508667, "test_acc5": 95.01800246704101, "epoch": 281, "n_parameters": 44040424, "ema_test_loss": 0.8317881223152984, "ema_test_acc1": 81.42200255767823, "ema_test_acc5": 95.46000263427734}
{"train_lr": 1.976576856224742e-05, "train_loss": 2.6296293424378385, "test_loss": 0.872810817351847, "test_acc1": 80.93400238708496, "test_acc5": 95.0300025631714, "epoch": 282, "n_parameters": 44040424, "ema_test_loss": 0.8324357465361104, "ema_test_acc1": 81.42200241119384, "ema_test_acc5": 95.45800265380859}

=============================================================
And this is the infomation printed on terminal during training:

Test:  [32/33]  eta: 0:00:00  loss: 0.9552 (0.8471)  acc1: 77.6042 (81.2480)  acc5: 93.7500 (95.3440)  time: 0.2747  data: 0.0001  max mem: 18344
Test: Total time: 0:00:15 (0.4759 s / it)
* Acc@1 81.422 Acc@5 95.320 loss 0.844
Accuracy of the model_ema on the 50000 test images: 81.42%
Max accuracy of model_ema: **81.49%**

Program time 2 days, 1:47:36
Training time 1 day, 22:35:22
The best Top-1 accuracy is 81.49 %

Program all done.

**Comment by Osilly** [comment]
Thanks for your response! We previously did not reproduce the origin DeiT-base on 8 GPUs (batch size 8 * 128, obtain the best acc 81.44%), so we didn't try to reproduce the DeiT-base of Network Expansion on 8 GPUs. It is possible that the conditions applicable to DeiT-base and Network Expansion are different. Have you had the same thing happen to you? 
Anyway, thanks for the logs you provide!

**Comment by dingning97** [comment]
We did reproduce the official implementation of DeiT-Base successfully , using the codes from here https://github.com/facebookresearch/deit .  And we got 81.83% top-1 accucy on 8 V100 GPUs by running 
 ```bash
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --model deit_base_patch16_224 --batch-size 128 --model-ema --data-path /path/to/imagenet --output_dir /path/to/save
 ```
This is the last few lines of the training log during reproducing the original baseline:
**============================================
Epoch: [299]  [1230/1251]  eta: 0:00:12  lr: 0.000010  loss: 2.7455 (2.5988)  time: 0.5686  data: 0.0002  max mem: 18018
Epoch: [299]  [1240/1251]  eta: 0:00:06  lr: 0.000010  loss: 2.6579 (2.5975)  time: 0.5668  data: 0.0013  max mem: 18018
Epoch: [299]  [1250/1251]  eta: 0:00:00  lr: 0.000010  loss: 2.7889 (2.5997)  time: 0.5614  data: 0.0013  max mem: 18018
Epoch: [299] Total time: 0:11:57 (0.5732 s / it)
Averaged stats: lr: 0.000010  loss: 2.7889 (2.6006) 

Test:  [ 0/33]  eta: 0:04:54  loss: 0.4339 (0.4339)  acc1: 91.6667 (91.6667)  acc5: 97.9167 (97.9167)  time: 8.9238  data: 8.6357  max mem: 18018
Test:  [10/33]  eta: 0:00:24  loss: 0.6907 (0.6849)  acc1: 84.3750 (85.4640)  acc5: 97.3958 (97.2538)  time: 1.0693  data: 0.7853  max mem: 18018
Test:  [20/33]  eta: 0:00:09  loss: 0.7327 (0.7740)  acc1: 82.8125 (83.1597)  acc5: 96.8750 (96.2798)  time: 0.2880  data: 0.0003  max mem: 18018
Test:  [30/33]  eta: 0:00:01  loss: 0.9304 (0.8384)  acc1: 80.7292 (81.5524)  acc5: 94.2708 (95.6485)  time: 0.2854  data: 0.0002  max mem: 18018
Test:  [32/33]  eta: 0:00:00  loss: 0.9446 (0.8349)  acc1: 78.1250 (81.4720)  acc5: 94.2708 (95.6800)  time: 0.2782  data: 0.0001  max mem: 18018
Test: Total time: 0:00:18 (0.5472 s / it)
Acc@1 81.574 Acc@5 95.496 loss 0.838
Accuracy of the network on the 50000 test images: 81.6%
Max accuracy of network: 81.63%

Test:  [ 0/33]  eta: 0:03:52  loss: 0.4215 (0.4215)  acc1: 92.1875 (92.1875)  acc5: 97.9167 (97.9167)  time: 7.0310  data: 6.7420  max mem: 18018
Test:  [10/33]  eta: 0:00:26  loss: 0.6732 (0.6647)  acc1: 84.8958 (85.6534)  acc5: 97.3958 (97.3485)  time: 1.1398  data: 0.8384  max mem: 18018
Test:  [20/33]  eta: 0:00:10  loss: 0.7167 (0.7517)  acc1: 82.8125 (83.4325)  acc5: 96.8750 (96.5278)  time: 0.4695  data: 0.1656  max mem: 18018
Test:  [30/33]  eta: 0:00:01  loss: 0.9023 (0.8167)  acc1: 80.2083 (81.8716)  acc5: 94.2708 (95.8669)  time: 0.3353  data: 0.0416  max mem: 18018
Test:  [32/33]  eta: 0:00:00  loss: 0.9081 (0.8129)  acc1: 79.6875 (81.7280)  acc5: 94.2708 (95.9200)  time: 0.3275  data: 0.0415  max mem: 18018
Test: Total time: 0:00:19 (0.6005 s / it)
Acc@1 81.834 Acc@5 95.690 loss 0.815
Accuracy of the model_ema on the 50000 test images: 81.83%
**=================================='

After this, we built our network expansion for ViT based on this official repo.
It is worth noting that "python==3.7 && numpy==1.21.6 && torch==1.7.0 && torchvision==0.8.1 && timm==0.3.2" is also used when reproducing official DeiT baseline.

**Comment by Osilly** [comment]
It looks like the EMA strategy can achieve better performance for DeiT-base in some cases. Thank you!
